# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Simulator Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - uses: maxim-lobanov/setup-xcode@v1
      with: 
        xcode-version: '16.1.0' 
    - name: Build
      run: xcodebuild -sdk iphonesimulator -configuration Debug -project "CalSnap.xcodeproj" -scheme "CalSnap"
   
